apiVersion: v1
kind: Deployment 
metadata:
  name: myapp-deployment
  labels:
    app: my-app
    type: front-end 

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: my-app
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80

replicas: 3
selector:
  matchLabels:
    type: front-end
